--- YOUR UP MIGRATION HERE ---
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--- YOUR DOWN MIGRATION HERE ---
DROP TABLE IF EXISTS users;